# Generated by Django 4.0.5 on 2022-07-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtaqueEspecial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del poder o habilidad')),
                ('descripcion', models.TextField(max_length=200, verbose_name='Detalle del poder o habilidad')),
                ('imagen', models.ImageField(blank=True, max_length=200, null=True, upload_to='Poderes/', verbose_name='Imagen poder')),
                ('daño_fisico', models.IntegerField(default=10, verbose_name='Daño fisico')),
                ('daño_magico', models.IntegerField(default=10, verbose_name='Daño magio')),
                ('categoria', models.PositiveIntegerField(choices=[(1, 'HABILIDAD'), (2, 'PODER')], verbose_name='Categoria del ataque especial')),
                ('estado', models.BooleanField(default=False, verbose_name='Inventario en uso')),
            ],
            options={
                'verbose_name': 'Ataque especial',
                'verbose_name_plural': 'Ataques especiales',
                'ordering': ['nombre'],
            },
        ),
    ]
