# Generated by Django 4.0.5 on 2022-07-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la raza')),
                ('descripcion', models.TextField(max_length=200, verbose_name='Detalle de la raza')),
                ('imagen', models.ImageField(blank=True, max_length=200, null=True, upload_to='raza/', verbose_name='Imagen de la raza')),
                ('estado', models.BooleanField(default=False, verbose_name='Raza activa')),
                ('dañoFisico', models.IntegerField(default=10, verbose_name='Daño fisico base')),
                ('dañoMagico', models.IntegerField(default=10, verbose_name='Daño magico base')),
                ('resistFisica', models.IntegerField(default=10, verbose_name='Armadura fisica')),
                ('resistMagica', models.IntegerField(default=10, verbose_name='Armadura magica')),
            ],
            options={
                'verbose_name': 'raza',
                'verbose_name_plural': 'Razas',
                'ordering': ['nombre'],
            },
        ),
    ]
