# Generated by Django 4.0.5 on 2022-07-18 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ataque', '0002_initial'),
        ('equipamiento', '0001_initial'),
        ('personaje', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventarioataque',
            name='ataque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ataque.ataqueespecial', verbose_name='Ataque especial'),
        ),
        migrations.AddField(
            model_name='inventarioataque',
            name='personaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaje.personaje', verbose_name='Personaje'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='objeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipamiento.objeto', verbose_name='Nombre objeto'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='personaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaje.personaje', verbose_name='Personaje'),
        ),
    ]
