# Generated by Django 4.0.5 on 2022-07-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True, verbose_name='Nombre objeto')),
                ('posicion', models.PositiveSmallIntegerField(choices=[(1, 'CASCO'), (2, 'PECHERA'), (3, 'GREVAS'), (4, 'BOTAS'), (5, 'ARMA PRINCIPAL'), (6, 'ARMA SECUNDARIA'), (7, 'POCION DE VIDA '), (8, 'POCION DE MANA '), (9, 'MONEDA ')], verbose_name='Posicion del objeto')),
                ('categoria', models.PositiveSmallIntegerField(blank=True, choices=[(5, 'PLATA'), (2, 'ESPADA'), (1, 'NINGUNA'), (3, 'BASTON'), (6, 'ORO'), (4, 'ARCO')], null=True, verbose_name='Categoria del objeto')),
                ('armaduraF', models.IntegerField(blank=True, default=0, null=True, verbose_name='Recistencia fisica')),
                ('armaduraM', models.IntegerField(blank=True, default=0, null=True, verbose_name='Recistencia Magica')),
                ('dañoF', models.IntegerField(blank=True, default=0, null=True, verbose_name='Daño fisico')),
                ('dañoM', models.IntegerField(blank=True, default=0, null=True, verbose_name='Daño magico')),
                ('imagen', models.ImageField(blank=True, max_length=200, null=True, upload_to='Objetos/', verbose_name='Imagen del objeto')),
                ('estado', models.BooleanField(default=False, verbose_name='Inventario en uso')),
            ],
            options={
                'verbose_name': 'Objeto',
                'verbose_name_plural': 'Objetos',
                'ordering': ['nombre'],
            },
        ),
    ]
